name: hydrosat-analytics-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  # Core scientific python
  - numpy
  - pyqt
  - tqdm
  - kiwisolver

  # Plotting
  - matplotlib
  - plotly
  - seaborn

  # hydrosat
  - shapely

  # For Synoptic Data
  - h5py
  - toml
  - black
  - isort
  - pylint
  - pytest
  - sphinx
  - nbsphinx
  - pydata-sphinx-theme # PyData Sphinx Theme (i.e, Numpy, Pandas, MetPy)
  - sphinx-panels # Add bootstrap elements to Sphinx
  - recommonmark
  - sphinx-markdown-tables
  - autodocsumm
  - sphinx-autosummary-accessors # pandas and xarray accessor docs
  - latexmk
  - myst-parser
  - linkify-it-py

  # Spatial packages
  - pysal
  - pyproj>=3.0
  - rasterstats
  - geopy
  - cartopy
  - descartes
  - contextily
  - earthpy
  - folium
  - geojson
  - mapboxgl
  - hydrofunctions
  - geocoder
  - tweepy
  - xarray
  - rioxarray>=0.3.0
  - scipy
  - netcdf4
  - nc-time-axis
  - regionmask
  - pygrib
  - pynio

  # Natural language processing
  - nltk
  - textblob

  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
  - nbresuse

  # Autograding
  - matplotcheck>=0.1.3
  - nbgrader
